steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - my-http-function
      - --region=asia-southeast1
      - --source=serverless
      - --trigger-http
      - --runtime=python312
      - --entry-point=hello
build:
  service_account: dsdsfdsfsdf@my-project-101-454903.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY  # Or set to NONE if you don't want logs
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET  # Optional if you want a regional bucket
