steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - my-http-function
      - --region=asia-southeast1
      - --source=serverless
      - --trigger-http
      - --runtime=python312
      - --entry-point=hello
build:
  service_account: your-service-account
options:
  logging: NONE
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
