steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - my-http-function
      - --region=asia-southeast1
      - --source=.
      - --trigger-http
      - --runtime=python312
      - --entry-point=hello
      - --gen2
      
options:
  logging: CLOUD_LOGGING_ONLY
