steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - my-http-function
      - --region=asia-southeast1
      - --source=serverless
      - --trigger-http
      - --runtime=python312
      - --entry-point=hello
build:
  service_account: fdsfdsfdsfdsf@my-project-101-454903.iam.gserviceaccount.com
  logs_bucket: gs://gcf-v2-sources-766657476274-asia-southeast1  # Specify the bucket for logs
options:
  logging: NONE  # or CLOUD_LOGGING_ONLY if you prefer Cloud Logging
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
