FROM python:3.13.2

WORKDIR /app
COPY app.py /app/app.py

RUN ["pip", "install", "fastapi[standard]"]
RUN ["pip", "install", "postgres"]
RUN ["pip", "install", "psycopg2"]

CMD ["fastapi", "run", "app.py"]